In [296]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import(
    OneHotEncoder,
    OrdinalEncoder,
    StandardScaler,
    MinMaxScaler
)
from sklearn.compose import ColumnTransformer

In [297]:
file_name = "Day12_Used_Car_Preprocessing_Dataset.csv"
car_data = pd.read_csv(file_name)
print("Dataset loaded successfully.")

Dataset loaded successfully.

In [298]:
print("========== DATASET SHAPE ==========")
print(f"Rows: {car_data.shape[0]}")
print(f"Columns: {car_data.shape[1]}")
print(f"Shape: {car_data.shape}")

========== DATASET SHAPE ==========
Rows: 320
Columns: 15
Shape: (320, 15)

In [299]:
print("========== COLUMN NAMES ==========")
for column_name in car_data.columns:
  print("-", column_name)

========== COLUMN NAMES ==========
- Car_ID
- Brand
- Year
- Mileage_Km
- Engine_CC
- Power_BHP
- Fuel_Type
- Transmission
- City
- Seller_Type
- Condition
- Previous_Owners
- Accidents_Reported
- Service_Score
- Resale_Price_Lakh

In [300]:
print("========== DATA TYPES ==========")
print(car_data.dtypes)

========== DATA TYPES ==========
Car_ID                 object
Brand                  object
Year                    int64
Mileage_Km              int64
Engine_CC               int64
Power_BHP             float64
Fuel_Type              object
Transmission           object
City                   object
Seller_Type            object
Condition              object
Previous_Owners         int64
Accidents_Reported      int64
Service_Score           int64
Resale_Price_Lakh     float64
dtype: object

In [301]:
print("========== DATASET INFORMATION ==========")
car_data.info()

========== DATASET INFORMATION ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Car_ID              320 non-null    object
 1   Brand               320 non-null    object
 2   Year                320 non-null    int64
 3   Mileage_Km          320 non-null    int64
 4   Engine_CC           320 non-null    int64
 5   Power_BHP           320 non-null    float64
 6   Fuel_Type           320 non-null    object
 7   Transmission        320 non-null    object
 8   City                320 non-null    object
 9   Seller_Type         320 non-null    object
 10  Condition           320 non-null    object
 11  Previous_Owners     320 non-null    int64
 12  Accidents_Reported  320 non-null    int64
 13  Service_Score       320 non-null    int64
 14  Resale_Price_Lakh   320 non-null    float64
dtypes: float64(2), int64(6), object(7)
memory usage: 37.6+ KB

In [302]:
print("========== DESCRIPTIVE STATISTICS ==========")
display(car_data.describe())

========== DESCRIPTIVE STATISTICS ==========

,Year,Mileage_Km,Engine_CC,Power_BHP,Previous_Owners,Accidents_Reported,Service_Score,Resale_Price_Lakh
count,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000,320.000000
mean,2019.537500,74110.203125,1346.703125,150.489688,1.668750,0.243750,76.203125,4.963031
std,3.341367,38885.260771,543.408160,36.665353,0.865369,0.528164,12.745864,3.359259
min,2014.000000,700.000000,600.000000,51.400000,1.000000,0.000000,55.000000,1.200000
25%,2017.000000,46323.250000,1004.750000,128.450000,1.000000,0.000000,64.750000,2.277500
50%,2020.000000,72718.500000,1303.000000,150.750000,1.000000,0.000000,77.000000,4.610000
75%,2022.000000,97951.500000,1635.250000,171.475000,2.000000,0.000000,87.000000,6.835000
max,2025.000000,320000.000000,5000.000000,390.000000,4.000000,2.000000,98.000000,28.500000

In [303]:
print("========== MISSING VALUES ==========")
missing_values = car_data.isnull().sum()
display(missing_values)
total_missing = missing_values.sum()
print(
    f"Total missing values: {total_missing}"
)

========== MISSING VALUES ==========

Car_ID                0
Brand                 0
Year                  0
Mileage_Km            0
Engine_CC             0
Power_BHP             0
Fuel_Type             0
Transmission          0
City                  0
Seller_Type           0
Condition             0
Previous_Owners       0
Accidents_Reported    0
Service_Score         0
Resale_Price_Lakh     0
dtype: int64

Total missing values: 0

In [304]:
print("========== DUPLICATE RECORDS ==========")
duplicate_count = car_data.duplicated().sum()
print(
    f"Number of duplicate rows: {duplicate_count}"
)

========== DUPLICATE RECORDS ==========
Number of duplicate rows: 0

In [305]:
if duplicate_count > 0:
  car_data = car_data.drop_duplicates()

  print(
      f"Duplicates removed successfully."
  )
else:
  print("No duplicate records found.")

No duplicate records found.

In [306]:
target_column = "Resale_Price_Lakh"
print(
    f"Target variable: {target_column}"
)

Target variable: Resale_Price_Lakh

In [307]:
car_data = car_data.drop(
    columns=["Car_ID"]
)
print(
    "Car_ID removed because it is an identifier"
)

Car_ID removed because it is an identifier

In [308]:
x = car_data.drop(
    columns=[target_column]
)
y = car_data[target_column]
print("========== FEATURES ==========")
print(x.columns.tolist())
print("\n========== TARGET ==========")
print(y.name)

========== FEATURES ==========
['Brand', 'Year', 'Mileage_Km', 'Engine_CC', 'Power_BHP', 'Fuel_Type', 'Transmission', 'City', 'Seller_Type', 'Condition', 'Previous_Owners', 'Accidents_Reported', 'Service_Score']

========== TARGET ==========
Resale_Price_Lakh

In [309]:
numerical_features = x.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()
categorical_features = x.select_dtypes(
    include=["object"]
).columns.tolist()
print("========== NUMERICAL FEATURES ==========")
for feature in numerical_features:
  print("-", feature)

print("\n========== CATEGORICAL FEATURES ==========")
for feature in categorical_features:
  print("-", feature)

========== NUMERICAL FEATURES ==========
- Year
- Mileage_Km
- Engine_CC
- Power_BHP
- Previous_Owners
- Accidents_Reported
- Service_Score

========== CATEGORICAL FEATURES ==========
- Brand
- Fuel_Type
- Transmission
- City
- Seller_Type
- Condition

In [310]:
print("========== CATEGORICAL VALUES ==========")
for column_name in categorical_features:
  print(f"\n{column_name}:")

  print(
      sorted(
          x[column_name].dropna().unique()
      )
  )

========== CATEGORICAL VALUES ==========

Brand:
['Honda', 'Hyundai', 'Kia', 'Mahindra', 'Maruti', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen']

Fuel_Type:
['CNG', 'Diesel', 'Electric', 'Petrol']

Transmission:
['Automatic', 'Manual']

City:
['Ahmedabad', 'Bengaluru', 'Chandigarh', 'Delhi', 'Hyderabad', 'Jaipur', 'Kochi', 'Lucknow', 'Mumbai', 'Pune']

Seller_Type:
['Certified Dealer', 'Dealer', 'Individual']

Condition:
['Excellent', 'Fair', 'Good', 'Poor', 'Very Good']

In [311]:
ordinal_features = [
    "Condition"
]
nominal_features = [
    "Brand",
    "Fuel_Type",
    "Transmission",
    "City",
    "Seller_Type"
]
print("Ordinal features:")
print(ordinal_features)
print("\nNominal features:")
print(nominal_features)

Ordinal features:
['Condition']

Nominal features:
['Brand', 'Fuel_Type', 'Transmission', 'City', 'Seller_Type']

In [312]:
def find_iqr_outliers(data, column_name):
  """Find outliers in a numerical column using IQR."""

  q1 = data[column_name].quantile(0.25)
  q3 = data[column_name].quantile(0.75)
  iqr = q3 - q1
  lower_limit = q1 - (1.5 * iqr)
  upper_limit = q3 + (1.5 * iqr)
  outliers = data[
      (data[column_name] < lower_limit)
      | (data[column_name] > upper_limit)
  ]

  return outliers, lower_limit, upper_limit

In [313]:
print("========== IQR OUTLIER ANALYSIS ==========")
iqr_summary = []
for column_name in numerical_features:
  outliers, lower_limit, upper_limit = (
      find_iqr_outliers(
          car_data,
          column_name
      )
  )

  iqr_summary.append(
      {
          "Column": column_name,
          "Outlier_Count": len(outliers),
          "Lower_Limit": lower_limit,
          "Upper_Limit": upper_limit
      }
  )

iqr_summary = pd.DataFrame(iqr_summary)
display(iqr_summary)

========== IQR OUTLIER ANALYSIS ==========

               Column  Outlier_Count  Lower_Limit  Upper_Limit
0                Year              0    2009.5000    2029.5000
1          Mileage_Km              2  -31119.1250  175393.8750
2           Engine_CC              6      59.0000    2581.0000
3           Power_BHP              7      63.9125     236.0125
4     Previous_Owners             14      -0.5000       3.5000
5  Accidents_Reported             63       0.0000       0.0000
6       Service_Score              0      31.3750     120.3750

In [314]:
print("========== Z-SCORE OUTLIER ANALYSIS ==========")
z_score_summary = []
for column_name in numerical_features:
  mean_value = car_data[column_name].mean()
  standard_deviation = car_data[
      column_name
  ].std()

  if standard_deviation != 0:
    z_score = (
        car_data[column_name] - mean_value
    ) / standard_deviation

    outlier_count = (
        z_score.abs() > 3
    ).sum()

  else:
    outlier_count = 0

  z_score_summary.append(
      {
          "Column": column_name,
          "Z_Score_Outliers": outlier_count
      }
  )

z_score_summary = pd.DataFrame(
    z_score_summary
)

display(z_score_summary)

========== Z-SCORE OUTLIER ANALYSIS ==========

               Column  Z_Score_Outliers
0                Year                 0
1          Mileage_Km                 2
2           Engine_CC                 5
3           Power_BHP                 2
4     Previous_Owners                 0
5  Accidents_Reported                15
6       Service_Score                 0

In [315]:
print("========== OUTLIER METHOD COMPARISION ==========")
outlier_comparision = iqr_summary[
    ["Column", "Outlier_Count"]
].merge(
    z_score_summary,
    on="Column"
)

display(outlier_comparision)

========== OUTLIER METHOD COMPARISION ==========

               Column  Outlier_Count  Z_Score_Outliers
0                Year              0                 0
1          Mileage_Km              2                 2
2           Engine_CC              6                 5
3           Power_BHP              7                 2
4     Previous_Owners             14                 0
5  Accidents_Reported             63                15
6       Service_Score              0                 0

In [316]:
car_data_cleaned = car_data.copy()
for column_name in numerical_features:
  q1 = car_data_cleaned[
      column_name
  ].quantile(0.25)
  q3 = car_data_cleaned[
      column_name
  ].quantile(0.75)

  iqr = q3 - q1
  lower_limit = q1 - (1.5 * iqr)
  upper_limit = q3 + (1.5 * iqr)
  car_data_cleaned[column_name] = (
      car_data_cleaned[column_name].clip(
          lower=lower_limit,
          upper=upper_limit
      )
  )

print(
    "Outliers capped using IQR limits"
)

Outliers capped using IQR limits

In [317]:
print("========== OUTLIERS AFTER IQR CAPPING ==========")
remaining_outliers = []
for column_name in numerical_features:
  outliers, lower_limit, upper_limit = (
      find_iqr_outliers(
          car_data_cleaned,
          column_name
      )
  )

  remaining_outliers.append(
      {
          "Column": column_name,
          "Remaining_Outliers": len(outliers)
      }
  )

remianing_outliers = pd.DataFrame(
    remaining_outliers
)
display(remaining_outliers)

========== OUTLIERS AFTER IQR CAPPING ==========

[{'Column': 'Year', 'Remaining_Outliers': 0},
 {'Column': 'Mileage_Km', 'Remaining_Outliers': 0},
 {'Column': 'Engine_CC', 'Remaining_Outliers': 0},
 {'Column': 'Power_BHP', 'Remaining_Outliers': 0},
 {'Column': 'Previous_Owners', 'Remaining_Outliers': 0},
 {'Column': 'Accidents_Reported', 'Remaining_Outliers': 0},
 {'Column': 'Service_Score', 'Remaining_Outliers': 0}]

In [318]:
x = car_data_cleaned.drop(
    columns=[target_column]
)
y = car_data_cleaned[target_column]

In [319]:
x_train, x_test, y_train, y_test = (
    train_test_split(
        x,
        y,
        test_size=0.20,
        random_state=42
    )
)
print("========== TRAIN-TEST SPLIT ==========")
print(f"Training rows: {x_train.shape[0]}")
print(f"Testing rows: {x_test.shape[0]}")
print(f"Training columns: {x_train.shape[1]}")
print(f"Testing columns: {x_test.shape[1]}")

========== TRAIN-TEST SPLIT ==========
Training rows: 256
Testing rows: 64
Training columns: 13
Testing columns: 13

In [320]:
one_hot_encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

In [321]:
condition_order = [
    [
        "Poor",
        "Fair",
        "Good",
        "Very Good",
        "Excellent"
    ]
]

ordinal_encoder = OrdinalEncoder(
    categories=condition_order,
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

In [322]:
standard_scaler = StandardScaler()

In [323]:
min_max_scaler = MinMaxScaler()

In [324]:
standard_preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            standard_scaler,
            numerical_features
        ),
        (
            "nominal",
            one_hot_encoder,
            nominal_features
        ),
        (
            "ordinal",
            ordinal_encoder,
            ordinal_features
        )
    ],
    remainder="drop"
)

In [325]:
x_train_standard = (
    standard_preprocessor.fit_transform(
        x_train
    )
)

x_test_standard = (
    standard_preprocessor.transform(
        x_test
    )
)

print("Standardization fitted only on training data.")
print(
    f"Processed training shape: "
    f"{x_train_standard.shape}"
)
print(
    f"Processed testing shape: "
    f"{x_test_standard.shape}"
)

Standardization fitted only on training data.
Processed training shape: (256, 37)
Processed testing shape: (64, 37)

In [326]:
min_max_preprocessor = ColumnTransformer(
    transformers=[
        (
            "numerical",
            min_max_scaler,
            numerical_features
        ),
        (
            "nominal",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            ),
            nominal_features
        ),
        (
            "ordinal",
            OrdinalEncoder(
                categories=condition_order,
                handle_unknown="use_encoded_value",
                unknown_value=-1
            ),
            ordinal_features
        )
    ],
    remainder="drop"
)

In [327]:
x_train_min_max = (
    min_max_preprocessor.fit_transform(
        x_train
    )
)

x_test_min_max = (
    min_max_preprocessor.transform(
        x_test
    )
)

print("Min-Max preprocessing completed.")
print(
    f"Min-Max training shape: "
    f"{x_train_min_max.shape}"
)
print(
    f"Min-Max testing shape: "
    f"{x_test_min_max.shape}"
)

Min-Max preprocessing completed.
Min-Max training shape: (256, 37)
Min-Max testing shape: (64, 37)

In [328]:
feature_names = (
    standard_preprocessor
    .get_feature_names_out()
)
print("========== PROCESSED FEATURES ==========")
for feature_name in feature_names:
  print("-", feature_name)

========== PROCESSED FEATURES ==========
- numerical__Year
- numerical__Mileage_Km
- numerical__Engine_CC
- numerical__Power_BHP
- numerical__Previous_Owners
- numerical__Accidents_Reported
- numerical__Service_Score
- nominal__Brand_Honda
- nominal__Brand_Hyundai
- nominal__Brand_Kia
- nominal__Brand_Mahindra
- nominal__Brand_Maruti
- nominal__Brand_Renault
- nominal__Brand_Skoda
- nominal__Brand_Tata
- nominal__Brand_Toyota
- nominal__Brand_Volkswagen
- nominal__Fuel_Type_CNG
- nominal__Fuel_Type_Diesel
- nominal__Fuel_Type_Electric
- nominal__Fuel_Type_Petrol
- nominal__Transmission_Automatic
- nominal__Transmission_Manual
- nominal__City_Ahmedabad
- nominal__City_Bengaluru
- nominal__City_Chandigarh
- nominal__City_Delhi
- nominal__City_Hyderabad
- nominal__City_Jaipur
- nominal__City_Kochi
- nominal__City_Lucknow
- nominal__City_Mumbai
- nominal__City_Pune
- nominal__Seller_Type_Certified Dealer
- nominal__Seller_Type_Dealer
- nominal__Seller_Type_Individual
- ordinal__Condition

In [329]:
x_train_processed = pd.DataFrame(
    x_train_standard,
    columns=feature_names,
    index=x_train.index
)
x_test_processed = pd.DataFrame(
    x_test_standard,
    columns=feature_names,
    index=x_test.index
)

print("Processed DataFrames created successfully.")

Processed DataFrames created successfully.

In [332]:
train_processed = x_train_processed.copy()
train_processed[target_column] = y_train
test_processed = x_test_processed.copy()
test_processed[target_column] = y_test

In [333]:
print("========== PROCESSED TRAINING DATA ==========")
display(train_processed.head())

========== PROCESSED TRAINING DATA ==========

,numerical__Year,numerical__Mileage_Km,numerical__Engine_CC,numerical__Power_BHP,numerical__Previous_Owners,numerical__Accidents_Reported,numerical__Service_Score,nominal__Brand_Honda,nominal__Brand_Hyundai,nominal__Brand_Kia,...,nominal__City_Jaipur,nominal__City_Kochi,nominal__City_Lucknow,nominal__City_Mumbai,nominal__City_Pune,nominal__Seller_Type_Certified Dealer,nominal__Seller_Type_Dealer,nominal__Seller_Type_Individual,ordinal__Condition,Resale_Price_Lakh
132,-0.486391,-0.225904,-0.322825,0.303144,-0.755752,0.0,-0.454105,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,3.0,4.26
317,0.725445,0.089296,-0.656909,-0.328921,-0.755752,0.0,-0.614672,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,5.30
234,-1.395268,1.115547,-0.120148,0.418918,-0.755752,0.0,-0.534389,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.23
312,1.028404,-0.195102,0.481202,0.412660,0.484456,0.0,0.188165,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,7.09
232,-1.092309,0.706499,0.788558,-0.435309,0.484456,0.0,0.107881,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,2.69

In [334]:
print("========== PROCESSED TESTING DATA ==========")
display(test_processed.head())

========== PROCESSED TESTING DATA ==========

,numerical__Year,numerical__Mileage_Km,numerical__Engine_CC,numerical__Power_BHP,numerical__Previous_Owners,numerical__Accidents_Reported,numerical__Service_Score,nominal__Brand_Honda,nominal__Brand_Hyundai,nominal__Brand_Kia,...,nominal__City_Jaipur,nominal__City_Kochi,nominal__City_Lucknow,nominal__City_Mumbai,nominal__City_Pune,nominal__Seller_Type_Certified Dealer,nominal__Seller_Type_Dealer,nominal__Seller_Type_Individual,ordinal__Condition,Resale_Price_Lakh
167,-0.486391,0.908183,-1.632432,-0.970374,-0.755752,0.0,-0.373821,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,1.62
230,1.331363,-0.926895,0.786331,-0.225663,0.484456,0.0,-1.337226,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,3.0,8.35
25,-1.092309,0.710145,-1.416391,-0.707535,-0.755752,0.0,1.552989,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,2.11
63,-0.486391,0.866416,-1.632432,-0.773244,0.484456,0.0,1.071286,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,2.82
9,-1.395268,2.143692,-0.002105,0.099756,-0.755752,0.0,-0.775240,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,1.20

In [335]:
print("========== STADARDIZED NUMERICAL FEATURES ==========")
standardized_columns = [
    column_name
    for column_name in x_train_processed.columns
    if column_name.startswith(
        "numerical__"
    )
]

display(
    x_train_processed[
        standardized_columns
    ].describe()
)

========== STADARDIZED NUMERICAL FEATURES ==========

,numerical__Year,numerical__Mileage_Km,numerical__Engine_CC,numerical__Power_BHP,numerical__Previous_Owners,numerical__Accidents_Reported,numerical__Service_Score
count,2.560000e+02,2.560000e+02,2.560000e+02,2.560000e+02,2.560000e+02,256.0,2.560000e+02
mean,-3.816392e-17,-1.040834e-17,1.214306e-17,-1.734723e-16,-4.163336e-17,0.0,-6.938894e-18
std,1.001959e+00,1.001959e+00,1.001959e+00,1.001959e+00,1.001959e+00,0.0,1.001959e+00
min,-1.698227e+00,-2.046627e+00,-1.632432e+00,-2.697210e+00,-7.557515e-01,0.0,-1.738645e+00
25%,-7.893502e-01,-7.699804e-01,-7.120323e-01,-6.394782e-01,-7.557515e-01,0.0,-8.755947e-01
50%,1.195268e-01,-1.044397e-02,-5.555874e-02,1.214335e-02,-7.557515e-01,0.0,1.078813e-01
75%,7.254448e-01,6.887173e-01,6.944581e-01,6.582891e-01,4.844561e-01,0.0,7.501513e-01
max,1.634322e+00,2.884383e+00,2.779694e+00,2.687859e+00,2.344768e+00,0.0,1.713556e+00

In [337]:
min_max_feature_names = (
    min_max_preprocessor
    .get_feature_names_out()
)
min_max_training_data = pd.DataFrame(
    x_train_min_max,
    columns=min_max_feature_names
)
min_max_numerical_columns = [
    column_name
    for column_name in min_max_training_data.columns
    if column_name.startswith(
        "numerical__"
    )
]
print("========== MIN-MAX SCALED FEATURES ==========")
display(
    min_max_training_data[
        min_max_numerical_columns
    ].describe()
)

========== MIN-MAX SCALED FEATURES ==========

,numerical__Year,numerical__Mileage_Km,numerical__Engine_CC,numerical__Power_BHP,numerical__Previous_Owners,numerical__Accidents_Reported,numerical__Service_Score
count,256.000000,256.000000,256.000000,256.000000,256.000000,256.0,256.000000
mean,0.509588,0.415052,0.369988,0.500868,0.243750,0.0,0.503634
std,0.300658,0.203195,0.227092,0.186062,0.323158,0.0,0.290238
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
25%,0.272727,0.258902,0.208607,0.382118,0.000000,0.0,0.250000
50%,0.545455,0.412934,0.357395,0.503123,0.000000,0.0,0.534884
75%,0.727273,0.554723,0.527385,0.623112,0.400000,0.0,0.720930
max,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000

In [338]:
print("========== FINAL MISSING VALUE CHECK ==========")
print(
    "Training missing values:",
    train_processed.isnull().sum().sum()
)
print(
    "Testing missing values:",
    test_processed.isnull().sum().sum()
)

========== FINAL MISSING VALUE CHECK ==========
Training missing values: 0
Testing missing values: 0

In [339]:
print("========== FINAL PROCESSED DATA ==========")
print(
    f"Training dataset shape: "
    f"{train_processed.shape}"
)
print(
    f"Testing dataset shape: "
    f"{test_processed.shape}"
)

========== FINAL PROCESSED DATA ==========
Training dataset shape: (256, 38)
Testing dataset shape: (64, 38)

In [341]:
train_output_file = (
    "Day12_Processed_Used_Car_Train.csv"
)
train_processed.to_csv(
    train_output_file,
    index=False
)
print(
    f"Training dataset saved as "
    f"{train_output_file}"
)

Training dataset saved as Day12_Processed_Used_Car_Train.csv

In [342]:
test_output_file = (
    "Day_Processed_Used_Car_Test.csv"
)
test_processed.to_csv(
    test_output_file,
    index=False
)
print(
    f"Testing dataset saved as "
    f"{test_output_file}"
)

Testing dataset saved as Day_Processed_Used_Car_Test.csv

In [343]:
processed_data = pd.concat(
    [
        train_processed,
        test_processed
    ],
    axis=0
)
processed_data = processed_data.sort_index()
print(
    f"Final processed dataset shape: "
    f"{processed_data.shape}"
)
display(processed_data.head())

Final processed dataset shape: (320, 38)

,numerical__Year,numerical__Mileage_Km,numerical__Engine_CC,numerical__Power_BHP,numerical__Previous_Owners,numerical__Accidents_Reported,numerical__Service_Score,nominal__Brand_Honda,nominal__Brand_Hyundai,nominal__Brand_Kia,...,nominal__City_Jaipur,nominal__City_Kochi,nominal__City_Lucknow,nominal__City_Mumbai,nominal__City_Pune,nominal__Seller_Type_Certified Dealer,nominal__Seller_Type_Dealer,nominal__Seller_Type_Individual,ordinal__Condition,Resale_Price_Lakh
0,0.422486,-0.102187,-0.403005,-0.666857,-0.755752,0.0,-0.373821,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,2.0,6.38
1,0.119527,0.439622,-0.957583,-0.113018,-0.755752,0.0,0.830435,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,4.83
2,0.422486,-0.838671,0.251798,1.119822,0.484456,0.0,1.071286,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,7.30
3,-0.183432,-0.070000,1.639357,-0.041050,1.724664,0.0,-0.855524,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,4.0,3.82
4,-1.092309,0.788535,0.721742,1.748758,0.484456,0.0,0.589584,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,1.93

In [344]:
final_output_file = (
    "Day12_Preprocessed_Used_Car_Dataset.csv"
)
processed_data.to_csv(
    final_output_file,
    index=False
)
print(
    f"Final processed dataset exported as "
    f"{final_output_file}"
)

Final processed dataset exported as Day12_Preprocessed_Used_Car_Dataset.csv